# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://photography.bastardsbook.com
title: The Bastards Book of Photography
subtitle: An open-source guide to working with light
author: Dan Nguyen
simple_search: http://google.com/search
description: A visual guide to learning your camera's manual settings and taking photos without a flash. 

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: dan@danwin.com

# image handling
cover_img: ny-giants-super-bowl-parade-ticker-_-6838582959.jpg
images_dir: /assets/content/images
graphics_dir: /assets/content/graphics
large_images_dir: /assets/content/images/large
square_images_dir: /assets/content/images/square
inset_images_dir: /assets/content/images/inset




# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
data_dir : _data 
posts_dir: /lessons
permalink: /lessons/:title
feedback_url: "/about/#feedback"
source: source
destination: public
plugins: plugins
code_dir: code
category_dir: blog/categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 100          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: false       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
#default_asides: [asides/recent_posts.html, asides/github.html, asides/twitter.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: dannguyen
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: dancow
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 106012495399367722593
googleplus_hidden: false

# Pinboard
pinboard_user: dan_n
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: thebastardsbook
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-24985223-1

# Facebook Like
facebook_like: true

# Flickr User
flickr_user: zokuga
flickr_url: http://www.flickr.com/photos/zokuga